adb pull /system/lib64/android.frameworks.cameraservice.service@2.0.so
adb pull /system/lib64/android.hardware.camera.common@1.0.so
adb pull /system/lib64/android.hardware.camera.device@1.0.so
adb pull /system/lib64/android.hardware.camera.device@3.2.so
adb pull /system/lib64/android.hardware.camera.device@3.3.so
adb pull /system/lib64/android.hardware.camera.device@3.4.so
adb pull /system/lib64/android.hardware.camera.device@3.5.so
adb pull /system/lib64/android.hardware.camera.provider@2.4.so
adb pull /system/lib64/android.hardware.camera.provider@2.5.so
adb pull /system/lib64/libEngineerCameraHalAssistClientJNI.so
adb pull /system/lib64/libarcsoft_calibverify_TriCamera.so
adb pull /system/lib64/libcamera2ndk.so
adb pull /system/lib64/libcamera_client.so
adb pull /system/lib64/libcamera_metadata.so
adb pull /system/lib64/libcameraservice.so
adb pull /system/lib64/libdualcameraddm.so
adb pull /system/lib64/libjni_dualcamera.so
adb pull /system/lib64/libqvrcamera_client.qti.so
adb pull /system/lib64/vendor.oppo.hardware.camera.oppoAlgoProcessService@1.0.so
adb pull /system/lib64/vendor.oppo.hardware.camera.oppoHalAssist@1.0.so
adb pull /system/lib64/vndk-29/android.frameworks.cameraservice.common@2.0.so
adb pull /system/lib64/vndk-29/android.frameworks.cameraservice.device@2.0.so
adb pull /system/lib64/vndk-29/android.frameworks.cameraservice.service@2.0.so
adb pull /system/lib64/vndk-29/android.hardware.camera.common@1.0.so
adb pull /system/lib64/vndk-29/android.hardware.camera.device@1.0.so
adb pull /system/lib64/vndk-29/android.hardware.camera.device@3.2.so
adb pull /system/lib64/vndk-29/android.hardware.camera.device@3.3.so
adb pull /system/lib64/vndk-29/android.hardware.camera.device@3.4.so
adb pull /system/lib64/vndk-29/android.hardware.camera.device@3.5.so
adb pull /system/lib64/vndk-29/android.hardware.camera.metadata@3.2.so
adb pull /system/lib64/vndk-29/android.hardware.camera.metadata@3.3.so
adb pull /system/lib64/vndk-29/android.hardware.camera.metadata@3.4.so
adb pull /system/lib64/vndk-29/android.hardware.camera.provider@2.4.so
adb pull /system/lib64/vndk-29/android.hardware.camera.provider@2.5.so
adb pull /system/lib64/vndk-29/libcamera_metadata.so
adb pull /system/media/audio/ui/camera_click.ogg
adb pull /system/media/audio/ui/camera_focus.ogg
adb pull /system/media/theme/default/com.oppo.camera
adb pull /system/product/lib/libimscamera_jni.so
adb pull /system/product/lib/vendor.qti.hardware.camera.device@1.0.so
adb pull /system/product/lib64/libimscamera_jni.so
adb pull /system/product/lib64/vendor.qti.hardware.camera.device@1.0.so
adb pull /system/product/priv-app/ims/lib/arm64/libimscamera_jni.so
